### PR TITLE
Some awesome changes

### PR DESCRIPTION
**Pull request by edchiou**
- Target Number is now properly generated for Single Player
- NumberCircles and OperatorCircles now properly separate when not merged.
- Greatly improved responsiveness for dragging nodes
- RandomNumbers no longer generates similar targets & numbers together
- Added folder groups to organize our project
- Scoring mechanism works correctly (I think)
- Removed difficulty settings (for now, still thinking about how to scale difficulty properly)

### CODE REVIEW

**Comment by edchiou** [comment]
Much drag, such responsiveness

**Comment by edchiou** [comment]
Someone should try merging their local branch with this branch because I added folder groups to organize things. Want to get this merged in as soon as possible so we don't have complex merge conflicts further down the line.

**Comment by choucalate** [comment]
it says this can be auto merged though, what's wrong with merging directly into master? Do you want me to code review?

**Comment by edchiou** [comment]
Yeah, code review would be nice. I'm more concerned that people who haven't been pulling from master will get huge merge conflicts.

**Comment by choucalate** [comment]
ohhhh im just going to tag everyone here, and if they've pulled from master recently (in short, if you've merged recently, please respond to this pull request saying you've already pulled from master) @kel033 @tjlevine @kkolli 

I've pulled the most recent

**Comment by tjlevine** [comment]
I just rebased on top of master, so I'm up to date

**Comment by kkolli** [comment]
I'm up-to date as well

**Comment by choucalate** [comment]
cool merged!

**Pull request merged**
